---
title: "Data Combination"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

## Prepare 24-25 data

```{r}
F24_raw <- read_csv("data/Final Data Collection Fall 2024-Spring 2025.csv") |>
  select(Transect, Term, Measurement, Depth_cm = Depth) #|>
  #group_by(Transect) |>
  #mutate(
  #  Depth_cm = Depth_Measurement -Depth_Measurement[1]#) 

```

Read in older data, combine

```{r}
F21 <- read_csv("data/CoreTread_F21.csv") |>
  select(Transect, Trail_Width, Measurement_Point,
         Depth_Measurement) |>
  mutate(Date = "F2021")

S22 <- read_csv("data/CoreTread_S22.csv") |>
  select(Transect, Trail_Width, Measurement_Point,
         Depth_Measurement)|>
  mutate(Date = "S2022")

AY2425 <- F24_raw |>
  select(Transect, Term,
         Measurement_Point = Measurement,
         Depth_Measurement = Depth_cm)|>
  mutate(Date = Term) |>
  mutate(Transect = as.numeric(Transect)) |>
  select(-Term)

All_Measurements <- bind_rows(F21, S22, AY2425) |>
  drop_na(Measurement_Point)

All_Measurements_long <- drop_na(All_Measurements, Transect)

#need to do depth adjustment here because otherwise there are measurments before the trail starts. So first get rid of the values that weren't measured the first time by dropping the f2021 NAs, then use the first value for each transect to zero out the measurements
All_Measurements_wide <- All_Measurements_long |>
  select(-Trail_Width)|>
  pivot_wider(names_from = Date,
              values_from = Depth_Measurement,
              values_fn = mean) |>
  drop_na(F2021) |>
  group_by(Transect) |>
  mutate(F2024 = F24 - F24[1],
         S2025 = S25 - S25[1]) |>
  select(-F24, -S25)


```

Add changes

```{r}
Change_at_each_measure <- All_Measurements_wide |>
  mutate(
    F2021_to_S2022 = F2021 - S2022,
    F2021_to_F2024 = F2021 - F2024,
    F2021_to_S2025 = F2021 - S2025,
    S2022_to_F2024 = S2022 - F2024,
    S2022_to_S2025 = S2022 - S2025
  )|>
  select(-c(F2021, S2022, F2024, S2025))
  
Summary_Change_by_Transect <- 
  Change_at_each_measure |>
  mutate(
    F2021_to_S2022 = F2021_to_S2022 * 10,
    F2021_to_F2024 = F2021_to_F2024 * 10,
    F2021_to_S2025 = F2021_to_S2025 * 10,
    S2022_to_F2024 = S2022_to_F2024 * 10,
    S2022_to_S2025 = S2022_to_S2025 * 10
  ) |>
  group_by(Transect) |>
  summarize(
    F2021_to_S2022_cm2 = sum(F2021_to_S2022),
    F2021_to_F2024_cm2 = sum(F2021_to_F2024),
    F2021_to_S2025_cm2 = sum(F2021_to_S2025),
    S2022_to_F2024_cm2 = sum(S2022_to_F2024),
    S2022_to_S2025_cm2 = sum(S2022_to_S2025)
  )

write_csv(Summary_Change_by_Transect, "total change by transect in cm2.csv")
```
